import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css"; // toastify styles
import { Providers } from "./provider";

import localFont from "next/font/local";

const coolvetica = localFont({
  src: "../public/fonts/CoolveticaRg-Regular.ttf",
  variable: "--font-coolvetica",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "PM Bitechx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${coolvetica.variable} font-sans`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
